Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false